dist: focal
os: linux
language: c
branches:
  only:
  - master
  - travis
jobs:
  include:
    - stage: "Compile"
      name: "Build binaries"
      arch: amd64
      os: linux
      script: travis_retry sudo make -C tests build
      workspaces:
        create:
          name: binaries
          paths:
            - .build
            - .tests
    - stage: "Testing"
      name: "Root on LUKS"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-luks"
      workspaces:
        use: binaries
    - name: "Root on LUKS with separate key"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-lukskey"
      workspaces:
        use: binaries
    - name: "Root on partition and unaccessible LUKS partition"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-luks-home"
      workspaces:
        use: binaries
    - name: "Root on LVM"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-lvm"
      workspaces:
        use: binaries
    - name: "Root on LVM with LUKS home partition"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-lvm-luks-home"
      workspaces:
        use: binaries
    - name: "Root on RAID1"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-raid1"
      workspaces:
        use: binaries
    - name: "Root on RAID1+RAID5"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-raid1+raid5"
      workspaces:
        use: binaries
    - name: "Root on degraded RAID1"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-degraded-raid1"
      workspaces:
        use: binaries
    - name: "Root on partition"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-partition"
      workspaces:
        use: binaries
    - name: "Root on squashfs from isofs"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-pipeline-iso-squash"
      workspaces:
        use: binaries
    - name: "Root on btrfs"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-btrfs-multi-device"
      workspaces:
        use: binaries
    - name: "Root on btrfs with subvol"
      arch: amd64
      os: linux
      env:
         - TRAVIS_TESTCASE="test-btrfs-subvol"
      workspaces:
        use: binaries
install:
  - sudo apt-get update -qq
  - sudo apt-get install coreutils cpio curl qemu-kvm
  - |
    sudo modprobe kvm-intel nested=1 ||:
    sudo modprobe kvm-amd   nested=1 ||:
script: travis_retry sudo make -C tests $TRAVIS_TESTCASE
